apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: task-mgmt
  labels:
    app: api
    tier: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    name: http
  selector:
    app: api