[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Target Python 3.12+
target-version = "py312"

[tool.ruff.lint]
# Enable essential linting rules
select = [
    "E",   # pycodestyle
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "W",   # pycodestyle warnings
    "C90", # mccabe complexity
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "PL",  # Pylint
    "RUF", # Ruff-specific rules
    "ANN", # flake8-annotations (type hints)
    "D",   # pydocstyle
]
# Explicitly ignore specific rules if needed
ignore = [
    "D203",   # one-blank-line-before-class
    "D212",   # multi-line-summary-first-line
]

# Type checking configuration
[tool.pyright]
# Basic settings
reportMissingImports = false
reportMissingTypeStubs = false
useLibraryCodeForTypes = true

# More specific settings to reduce noise
reportGeneralTypeIssues = false
reportOptionalSubscript = false
reportOptionalMemberAccess = false
reportOptionalCall = false
reportOptionalIterable = false
reportOptionalContextManager = false
reportOptionalOperand = false
reportTypedDictNotRequiredAccess = false
reportUnknownParameterType = false
reportUnknownArgumentType = false
reportUnknownLambdaType = false
reportUnknownMemberType = false

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
known-first-party = ["app"]
