apiVersion: v1
kind: Service
metadata:
  name: api-nodeport
  namespace: task-mgmt
  labels:
    app: api
    tier: external
spec:
  type: NodePort
  ports:
  - port: 8000        # Port on the service
    targetPort: 8000  # Port on the API pods
    nodePort: 30080   # External port (30000-32767 range)
    name: http
  selector:
    app: api          # Routes to pods with app=api label